name: Pull Release Label Toggle
description: Creates or updates a PR label based on Success or Failure of GitHub Action Steps

branding:
  icon: 'book_open'
  color: 'blue'
inputs:
  status_true_message:
    description: This is a word like Passing, Success, Found, or 👍
    required: false
  status_false_message:
    description: This is a word like Error, Failure, Success, Not Found, or 👎
    required: false
  label_prefix:
    description: The prefix of the label to toggle like Unit Tests, DB Dump
    required: false
  status:
    description: >
      This is a boolean status that can be passed in to override the detected status.
    required: false
    default: false
  github_token:
    description: >
      The GitHub token to use for authentication.
    required: false
    default: ${{github.token}}
  pr_number:
    description: >
      The PR number to change the labels on. This is used when the action is triggered
      by something other than a PR such as a PR comment, or a push, or anything else.
    required: false
    default: ${{github.number}}
  repository:
    description: >
      If not provided, this is the same as github.repository i.e:
      The owner and repository name. For example, Codertocat/Hello_World
    required: false
  generate_only:
    description: If true, do not update the label, just output the generated name
    required: false
    default: false
  use_emoji:
    description: Switch the default `Success` to `✅` and `Failed` to `❌`
    required: false
    default: false
  use_job_name_as_prefix:
    required: false
    default: false
    description: |
      the label prefix will be generated from the current action's job name:
      underscores and hyphens are turned to spaces, first letter of each word
      is capitalized.
      Means the `label_prefix` can be empty.
      `unit_tests` -> `Unit Tests`
      `spellcheck` -> `Spellcheck`

outputs:
  add_label_name:
    description: The label name to add
  remove_label_name:
    description: The label name to remove
  repository:
    description: The repository to update
  pr_number:
    description: The pull request that is updated
runs:
  using: 'node16'
  main: 'lib/main.mjs'
